import { mockCreators } from "@/entities/users/constants/mockUsers";
import type { BuildListItem } from "../types/build-card";

const [
  builderBlock,
  redstoneWizard,
  sakuraLover,
  voxelExplorer,
  minecraftGuy99,
  pixelPainter,
] = mockCreators;

export const mockBuilds: BuildListItem[] = [
  {
    id: "zephyr-cloud-castle",
    title: "Zephyr Cloud Castle & Gardens",
    category: "Castles",
    tags: ["Fantasy", "Sky", "MegaBuild"],
    author: builderBlock,
    previewTone: "violet",
    likes: 1240,
    comments: 42,
    downloads: 4821,
    isLiked: false,
    footprint: 96,
    blocks: 184000,
    versions: ["1.21", "1.20"],
    bedrockReady: false,
    hasRedstone: false,
    survivalFriendly: true,
    hasSchematic: true,
    publishedAt: "2026-03-12",
  },
  {
    id: "emerald-sky-fortress",
    title: "Emerald Sky Fortress",
    category: "Castles",
    tags: ["Fantasy", "Sky"],
    author: builderBlock,
    previewTone: "emerald",
    likes: 312,
    comments: 24,
    downloads: 118,
    isLiked: false,
    footprint: 48,
    blocks: 42000,
    versions: ["1.21"],
    bedrockReady: false,
    hasRedstone: false,
    survivalFriendly: true,
    hasSchematic: true,
    publishedAt: "2026-02-02",
  },
  {
    id: "bamboo-farm",
    title: "Fully Automatic Bamboo Farm",
    category: "Redstone",
    tags: ["Farm", "Automatic"],
    author: redstoneWizard,
    previewTone: "amber",
    likes: 874,
    comments: 57,
    downloads: 3106,
    isLiked: true,
    footprint: 24,
    blocks: 8400,
    versions: ["1.21", "1.20", "1.16"],
    bedrockReady: false,
    hasRedstone: true,
    survivalFriendly: true,
    hasSchematic: true,
    publishedAt: "2026-04-01",
  },
  {
    id: "iron-farm-starter",
    title: "Iron Farm Starter Kit",
    category: "Redstone",
    tags: ["Farm", "SurvivalFriendly"],
    author: redstoneWizard,
    previewTone: "stone",
    likes: 502,
    comments: 38,
    downloads: 2740,
    isLiked: false,
    footprint: 16,
    blocks: 3200,
    versions: ["1.20", "1.16"],
    bedrockReady: true,
    hasRedstone: true,
    survivalFriendly: true,
    hasSchematic: true,
    publishedAt: "2026-01-18",
  },
  {
    id: "sakura-shrine",
    title: "Sakura Shrine Courtyard",
    category: "Organic",
    tags: ["Japan", "Garden"],
    author: sakuraLover,
    previewTone: "sakura",
    likes: 640,
    comments: 29,
    downloads: 1220,
    isLiked: true,
    footprint: 32,
    blocks: 21000,
    versions: ["1.21", "1.20"],
    bedrockReady: true,
    hasRedstone: false,
    survivalFriendly: true,
    hasSchematic: true,
    publishedAt: "2026-03-28",
  },
  {
    id: "cherry-blossom-village",
    title: "Cherry Blossom Village",
    category: "Organic",
    tags: ["Village", "Japan"],
    author: sakuraLover,
    previewTone: "emerald",
    likes: 418,
    comments: 22,
    downloads: 905,
    isLiked: false,
    footprint: 64,
    blocks: 96000,
    versions: ["1.21"],
    bedrockReady: false,
    hasRedstone: false,
    survivalFriendly: true,
    hasSchematic: false,
    publishedAt: "2026-02-20",
  },
  {
    id: "neon-skyline",
    title: "Neon Skyline District",
    category: "Sci-Fi",
    tags: ["City", "Cyberpunk"],
    author: voxelExplorer,
    previewTone: "ocean",
    likes: 1105,
    comments: 64,
    downloads: 2310,
    isLiked: false,
    footprint: 128,
    blocks: 512000,
    versions: ["1.21", "1.20"],
    bedrockReady: false,
    hasRedstone: true,
    survivalFriendly: false,
    hasSchematic: true,
    publishedAt: "2026-04-10",
  },
  {
    id: "orbital-lab",
    title: "Orbital Research Lab",
    category: "Sci-Fi",
    tags: ["Space", "Mechanical"],
    author: voxelExplorer,
    previewTone: "violet",
    likes: 733,
    comments: 31,
    downloads: 1580,
    isLiked: false,
    footprint: 40,
    blocks: 38000,
    versions: ["1.21"],
    bedrockReady: false,
    hasRedstone: true,
    survivalFriendly: false,
    hasSchematic: true,
    publishedAt: "2026-03-05",
  },
  {
    id: "cozy-starter-base",
    title: "Cozy Survival Starter Base",
    category: "Survival",
    tags: ["House", "Cozy"],
    author: minecraftGuy99,
    previewTone: "amber",
    likes: 289,
    comments: 16,
    downloads: 1490,
    isLiked: true,
    footprint: 16,
    blocks: 2400,
    versions: ["1.21", "1.20", "1.16"],
    bedrockReady: true,
    hasRedstone: false,
    survivalFriendly: true,
    hasSchematic: true,
    publishedAt: "2026-04-16",
  },
  {
    id: "cliffside-storage",
    title: "Cliffside Storage Hall",
    category: "Survival",
    tags: ["Storage", "SurvivalFriendly"],
    author: minecraftGuy99,
    previewTone: "stone",
    likes: 356,
    comments: 21,
    downloads: 980,
    isLiked: false,
    footprint: 32,
    blocks: 15600,
    versions: ["1.20"],
    bedrockReady: true,
    hasRedstone: true,
    survivalFriendly: true,
    hasSchematic: true,
    publishedAt: "2026-01-29",
  },
  {
    id: "portrait-mosaic",
    title: "Portrait Mosaic Wall",
    category: "Pixel Art",
    tags: ["Mosaic", "Portrait"],
    author: pixelPainter,
    previewTone: "violet",
    likes: 244,
    comments: 12,
    downloads: 610,
    isLiked: true,
    footprint: 64,
    blocks: 4096,
    versions: ["1.21", "1.20", "1.16"],
    bedrockReady: true,
    hasRedstone: false,
    survivalFriendly: true,
    hasSchematic: true,
    publishedAt: "2026-03-19",
  },
  {
    id: "retro-arcade-set",
    title: "Retro Arcade Pixel Set",
    category: "Pixel Art",
    tags: ["Mosaic", "Retro"],
    author: pixelPainter,
    previewTone: "amber",
    likes: 198,
    comments: 9,
    downloads: 430,
    isLiked: false,
    footprint: 24,
    blocks: 1800,
    versions: ["1.21"],
    bedrockReady: true,
    hasRedstone: false,
    survivalFriendly: true,
    hasSchematic: false,
    publishedAt: "2026-04-04",
  },
  {
    id: "modern-glass-villa",
    title: "Modern Glass Villa",
    category: "Modern",
    tags: ["House", "Minimal"],
    author: builderBlock,
    previewTone: "ocean",
    likes: 521,
    comments: 27,
    downloads: 1340,
    isLiked: false,
    footprint: 48,
    blocks: 28000,
    versions: ["1.21", "1.20"],
    bedrockReady: false,
    hasRedstone: false,
    survivalFriendly: true,
    hasSchematic: true,
    publishedAt: "2026-02-11",
  },
  {
    id: "stone-keep-barracks",
    title: "Stone Keep & Barracks",
    category: "Medieval",
    tags: ["Castle", "Village"],
    author: builderBlock,
    previewTone: "stone",
    likes: 467,
    comments: 33,
    downloads: 1120,
    isLiked: false,
    footprint: 64,
    blocks: 74000,
    versions: ["1.20", "1.16"],
    bedrockReady: true,
    hasRedstone: false,
    survivalFriendly: true,
    hasSchematic: true,
    publishedAt: "2026-01-08",
  },
];
