export const buildDetailsLabels = {
  category: "Castles",
  title: "Zephyr Cloud Castle & Gardens",
  author: "BuilderBlock",
  publishedAt: "Published March 12, 2026",
  followCreator: "+ Follow Creator",
  galleryAriaLabel: "Build gallery",
  visualizerTitle: "3D Visualization",
  visualizerPlaceholder: "3D preview placeholder",
  aboutTitle: "About this Build",
  description:
    "An astronomical palace floating gracefully above the cloud line. Features fully detailed interior banquet halls, a master bedroom in the central spire, auto-harvesting wheat and melon crops in the hanging gardens, and three custom-designed waterfalls cascading into the void. Completely built in Survival over the course of 3 months. Perfect as a base or spawn hub!",
  tags: ["Fantasy", "Sky", "MegaBuild", "SurvivalFriendly", "Waterfalls"],
  getBuildTitle: "Get this Build",
  likesLabel: "Likes",
  likesValue: "1,240",
  downloadsLabel: "Downloads",
  downloadsValue: "4,821",
  downloadSchematic: "Download Schematic",
  addToFavorites: "Add to Favorites",
  relatedTitle: "Related Builds",
  relatedBuilds: [
    {
      id: "related-1",
      title: "Emerald Sky Fortress",
      author: "Steve",
      imageUrl: "/icons/logo-cube.svg",
      avatarUrl: "/icons/logo-cube.svg",
      category: "Castles",
      tags: ["Fantasy", "Sky"],
      likes: 312,
      countComments: 24,
      countDownloads: 118,
      isLiked: false,
    },
    {
      id: "related-2",
      title: "Forest Survival Base",
      author: "Alex",
      imageUrl: "/icons/logo-cube.svg",
      avatarUrl: "/icons/logo-cube.svg",
      category: "Survival",
      tags: ["Organic", "Base"],
      likes: 205,
      countComments: 16,
      countDownloads: 92,
      isLiked: false,
    },
    {
      id: "related-3",
      title: "Ancient Garden Keep",
      author: "Builder",
      imageUrl: "/icons/logo-cube.svg",
      avatarUrl: "/icons/logo-cube.svg",
      category: "Medieval",
      tags: ["Garden", "Castle"],
      likes: 184,
      countComments: 11,
      countDownloads: 76,
      isLiked: false,
    },
    {
      id: "related-4",
      title: "Floating Village Hub",
      author: "Notch",
      imageUrl: "/icons/logo-cube.svg",
      avatarUrl: "/icons/logo-cube.svg",
      category: "Fantasy",
      tags: ["Village", "Sky"],
      likes: 267,
      countComments: 19,
      countDownloads: 104,
      isLiked: false,
    },
  ],
};
