export const uploadBuildLabels = {
  eyebrow: "New Build",
  title: "Upload a Minecraft Build",
  description:
    "Add screenshots, a schematic file, category, and tags so other creators can discover and download your build.",
  draftStatus: "Draft preview",
  formTitle: "Build Details",
  formDescription:
    "These fields map to the build model: title, description, photos, schematicUrl, category, tags, and publish metadata.",
  mediaTitle: "Photos",
  mediaDescription:
    "Upload the main cover image first, then add extra gallery shots.",
  schematicTitle: "Schematic File",
  schematicDescription: "Attach a .schem or .litematic file for downloads.",
  previewTitle: "Live Preview",
  publishChecklistTitle: "Publish Checklist",
  uploadPhotos: "Drop photos here or browse",
  uploadSchematic: "Drop schematic file here or browse",
  publish: "Publish Build",
  saveDraft: "Save Draft",
  coverHint: "PNG, JPG, or WEBP up to 10MB",
  schematicHint: ".schem, .schematic, or .litematic",
  fields: {
    title: "Title",
    titlePlaceholder: "Zephyr Cloud Castle & Gardens",
    description: "Description",
    descriptionPlaceholder:
      "Tell builders what makes this project special, how it was built, and what is included...",
    category: "Category",
    tags: "Tags",
    tagsPlaceholder: "Fantasy, Sky, MegaBuild",
  },
  categories: [
    "Castles",
    "Redstone",
    "Pixel Art",
    "Survival",
    "Medieval",
    "Sci-Fi",
    "Organic",
    "Modern",
  ],
  selectedCategory: "Castles",
  suggestedTags: ["Fantasy", "Sky", "MegaBuild", "SurvivalFriendly"],
  checklist: [
    "At least one photo",
    "Clear title and description",
    "Category selected",
    "Schematic file attached",
  ],
  preview: {
    title: "Zephyr Cloud Castle & Gardens",
    author: "BuilderBlock",
    category: "Castles",
    likes: 0,
    comments: 0,
    downloads: 0,
  },
};
